FROM node:20
# as build-stage
#alpine даёт ошибку

#TODO попробовать https://ru.vuejs.org/v2/cookbook/dockerize-vuejs-app.html

WORKDIR /frontend

ENV PATH /frontend/node_modules/.bin:$PATH

# COPY package.json /frontend/package.json
COPY package*.json ./

# RUN npm install --silent
# RUN npm install -g npm@latest
# RUN npm cache clean --force
# RUN npm rm -rf node_modules && rm package-lock.json
RUN npm install

COPY . .

# EXPOSE 8080

# все RUN выполняется только при сборке, CMD - каждый раз при запуске, и только последний
RUN npm run build
# указано в виде команды в compose YAML файле