# FROM nginx:latest
FROM owasp/modsecurity-crs:nginx-alpine

# COPY default.prod.conf /etc/nginx/conf.d/default.conf
COPY templates/default.conf.template /etc/nginx/templates/conf.d/default.conf.template

ENV TZ=UTC